@echo off
echo Setting Cloudflare API Token and running deployment...
set CLOUDFLARE_API_TOKEN=gZmPM0oTIikfopiJap3aIWFZBZmNAKPAZ3N3jI-Q
echo API Token set: %CLOUDFLARE_API_TOKEN:~0,10%...
echo Running deployment script...
node scripts/deploy-with-api-token.js
pause
