-- Sync SuperSaaS services to platform
-- Generated by scripts/supersaas-complete-sync.js

DELETE FROM services WHERE tenant_id = 'ccb12b4d-ade6-467d-a614-7c9d198ddc70';

INSERT INTO services (tenant_id, name, description, price, duration_minutes) VALUES
('ccb12b4d-ade6-467d-a614-7c9d198ddc70', 'Middle & Side Installation', 'Professional hair installation service for middle and side parts', 30000, 60);
INSERT INTO services (tenant_id, name, description, price, duration_minutes) VALUES
('ccb12b4d-ade6-467d-a614-7c9d198ddc70', 'Maphondo & Lines Installation', 'Traditional African hairstyling with intricate patterns', 35000, 60);
