#!/bin/bash
# HashiCorp Vault Secrets Retrieval Script for AppointmentBooking.co.za
# This script retrieves production secrets from HashiCorp Vault
# and outputs them for use in Cloudflare Pages deployment

set -e

# Configuration
VAULT_ADDR="${VAULT_ADDR:-https://vault.appointmentbooking.co.za:8200}"
VAULT_TOKEN="${VAULT_TOKEN:-}"
SECRETS_PATH="secret/data/appointmentbooking/production"
OUTPUT_FILE="apps/booking/.env.production.vault"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "=========================================="
echo "HashiCorp Vault Secrets Retrieval"
echo "=========================================="
echo "Vault Address: $VAULT_ADDR"
echo "Secrets Path: $SECRETS_PATH"
echo ""

# Check if Vault token is available
if [ -z "$VAULT_TOKEN" ]; then
    echo -e "${YELLOW}Warning: VAULT_TOKEN not set${NC}"
    echo "Attempting to use Vault agent sidecar or ~/.vault-token..."
    
    # Try to read from default token location
    if [ -f "$HOME/.vault-token" ]; then
        VAULT_TOKEN=$(cat "$HOME/.vault-token")
        echo "Using token from ~/.vault-token"
    else
        echo -e "${RED}Error: No Vault token available${NC}"
        echo "Please set VAULT_TOKEN environment variable or configure Vault agent"
        exit 1
    fi
fi

# Function to retrieve secret from Vault
get_vault_secret() {
    local secret_path=$1
    local field=$2
    
    curl -s -H "X-Vault-Token: $VAULT_TOKEN" \
         "$VAULT_ADDR/v1/$secret_path" | \
         jq -r ".data.data[\"$field\"] // empty"
}

# Function to get all secrets from path
get_vault_secrets() {
    local secret_path=$1
    
    curl -s -H "X-Vault-Token: $VAULT_TOKEN" \
         "$VAULT_ADDR/v1/$secret_path" | \
         jq -r '.data.data | to_entries[] | "\(.key)=\(.value)"'
}

# Check Vault connectivity
echo "Checking Vault connectivity..."
if curl -s -o /dev/null -w "%{http_code}" -H "X-Vault-Token: $VAULT_TOKEN" "$VAULT_ADDR/v1/sys/health" | grep -q "200\|429"; then
    echo -e "${GREEN}✓ Vault is accessible${NC}"
else
    echo -e "${RED}✗ Vault is not accessible${NC}"
    exit 1
fi

# Retrieve secrets from HashiCorp Vault
echo ""
echo "Retrieving production secrets..."

# Create output file header
cat > "$OUTPUT_FILE" << 'EOF'
# Production Environment Variables for AppointmentBooking.co.za
# Generated by vault-secrets-retrieval.sh
# WARNING: This file contains sensitive secrets - do not commit to version control

# ==========================================
# APPLICATION CONFIGURATION
# ==========================================
NODE_ENV=production
NEXT_PUBLIC_APP_URL=https://appointmentbooking.co.za
NEXTAUTH_URL=https://appointmentbooking.co.za

# ==========================================
# TENANT CONFIGURATION
# ==========================================
NEXT_PUBLIC_TENANT_ID=appointmentbooking-coza-tenant-id

# ==========================================
# SUPABASE (AI Memory & Chat History)
# ==========================================
EOF

# Get Supabase secrets
echo "Retrieving Supabase credentials..."
SUPABASE_URL=$(get_vault_secret "$SECRETS_PATH" "SUPABASE_URL")
SUPABASE_ANON_KEY=$(get_vault_secret "$SECRETS_PATH" "SUPABASE_ANON_KEY")
SUPABASE_SERVICE_ROLE_KEY=$(get_vault_secret "$SECRETS_PATH" "SUPABASE_SERVICE_ROLE_KEY")

cat >> "$OUTPUT_FILE" << EOF
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL:-https://your-project.supabase.co}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-your-anon-key}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-your-service-role-key}
EOF

# Add remaining configuration sections
cat >> "$OUTPUT_FILE" << 'EOF'

# ==========================================
# GOOGLE GEMINI (AI Agents) - Production Keys
# ==========================================
EOF

GEMINI_API_KEY=$(get_vault_secret "$SECRETS_PATH" "GEMINI_API_KEY")
cat >> "$OUTPUT_FILE" << EOF
GEMINI_API_KEY=${GEMINI_API_KEY:-your-production-gemini-api-key}
GOOGLE_API_KEY=${GEMINI_API_KEY:-your-production-gemini-api-key}
EOF

cat >> "$OUTPUT_FILE" << 'EOF'

# ==========================================
# AISENSY (WhatsApp Integration) - Production
# ==========================================
EOF

AISENSY_API_KEY=$(get_vault_secret "$SECRETS_PATH" "AISENSY_API_KEY")
AISENSY_WEBHOOK_SECRET=$(get_vault_secret "$SECRETS_PATH" "AISENSY_WEBHOOK_SECRET")
AISENSY_VERIFY_TOKEN=$(get_vault_secret "$SECRETS_PATH" "AISENSY_VERIFY_TOKEN")

cat >> "$OUTPUT_FILE" << EOF
AISENSY_API_KEY=${AISENSY_API_KEY:-your-production-aisensy-api-key}
AISENSY_CAMPAIGN_NAME=appointmentbooking-coza
AISENSY_WEBHOOK_SECRET=${AISENSY_WEBHOOK_SECRET:-your-production-webhook-secret}
AISENSY_VERIFY_TOKEN=${AISENSY_VERIFY_TOKEN:-appointmentbooking-coza-webhook-token}
EOF

cat >> "$OUTPUT_FILE" << 'EOF'

# ==========================================
# PAYSTACK (Payment Processing) - Live Keys
# ==========================================
EOF

PAYSTACK_PUBLIC_KEY=$(get_vault_secret "$SECRETS_PATH" "PAYSTACK_PUBLIC_KEY")
PAYSTACK_SECRET_KEY=$(get_vault_secret "$SECRETS_PATH" "PAYSTACK_SECRET_KEY")
PAYSTACK_WEBHOOK_SECRET=$(get_vault_secret "$SECRETS_PATH" "PAYSTACK_WEBHOOK_SECRET")

cat >> "$OUTPUT_FILE" << EOF
NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY=${PAYSTACK_PUBLIC_KEY:-pk_live_your-production-public-key}
PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY:-sk_live_your-production-secret-key}
PAYSTACK_WEBHOOK_SECRET=${PAYSTACK_WEBHOOK_SECRET:-your-production-paystack-webhook-secret}
EOF

cat >> "$OUTPUT_FILE" << 'EOF'

# ==========================================
# SENTRY (Error Tracking) - Production DSN
# ==========================================
EOF

SENTRY_DSN=$(get_vault_secret "$SECRETS_PATH" "SENTRY_DSN")
SENTRY_AUTH_TOKEN=$(get_vault_secret "$SECRETS_PATH" "SENTRY_AUTH_TOKEN")

cat >> "$OUTPUT_FILE" << EOF
NEXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN:-https://your-production-sentry-dsn@sentry.io/project-id}
SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN:-your-production-sentry-auth-token}
SENTRY_ORG=your-production-org
SENTRY_PROJECT=appointmentbooking-coza
EOF

cat >> "$OUTPUT_FILE" << 'EOF'

# ==========================================
# CLOUDFLARE (Hosting & CDN)
# ==========================================
CLOUDFLARE_ACCOUNT_ID=9e96c83268cae3e0f27168ed50c92033
CLOUDFLARE_API_TOKEN=your-production-cloudflare-token

# ==========================================
# CRON JOBS - Production Security
# ==========================================
EOF

CRON_SECRET=$(get_vault_secret "$SECRETS_PATH" "CRON_SECRET")
cat >> "$OUTPUT_FILE" << EOF
CRON_SECRET=${CRON_SECRET:-your-secure-production-cron-secret-256-bits}
EOF

cat >> "$OUTPUT_FILE" << 'EOF'

# ==========================================
# OAUTH PROVIDERS - Production Configuration
# ==========================================

# Google OAuth - Production
EOF

GOOGLE_CLIENT_ID=$(get_vault_secret "$SECRETS_PATH" "GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET=$(get_vault_secret "$SECRETS_PATH" "GOOGLE_CLIENT_SECRET")

cat >> "$OUTPUT_FILE" << EOF
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-your-production-google-client-id}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-your-production-google-client-secret}
GOOGLE_REDIRECT_URI=https://appointmentbooking.co.za/api/auth/callback/google

# Microsoft OAuth - Production
EOF

MICROSOFT_CLIENT_ID=$(get_vault_secret "$SECRETS_PATH" "MICROSOFT_CLIENT_ID")
MICROSOFT_CLIENT_SECRET=$(get_vault_secret "$SECRETS_PATH" "MICROSOFT_CLIENT_SECRET")

cat >> "$OUTPUT_FILE" << EOF
MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID:-your-production-microsoft-client-id}
MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET:-your-production-microsoft-client-secret}
MICROSOFT_REDIRECT_URI=https://appointmentbooking.co.za/api/auth/callback/microsoft

# ==========================================
# DATABASE - Production Connection
# ==========================================
EOF

DATABASE_URL=$(get_vault_secret "$SECRETS_PATH" "DATABASE_URL")
cat >> "$OUTPUT_FILE" << EOF
DATABASE_URL=${DATABASE_URL:-postgresql://username:password@host:port/database}
DATABASE_SSL=true
DATABASE_POOL_SIZE=20
EOF

cat >> "$OUTPUT_FILE" << 'EOF'

# ==========================================
# JWT & SESSION SECURITY - Production
# ==========================================
EOF

JWT_SECRET=$(get_vault_secret "$SECRETS_PATH" "JWT_SECRET")
NEXTAUTH_SECRET=$(get_vault_secret "$SECRETS_PATH" "NEXTAUTH_SECRET")
ENCRYPTION_KEY=$(get_vault_secret "$SECRETS_PATH" "ENCRYPTION_KEY")

cat >> "$OUTPUT_FILE" << EOF
JWT_SECRET=${JWT_SECRET:-your-production-jwt-secret-256-bits-minimum}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-production-nextauth-secret-256-bits}
SESSION_TIMEOUT=1800000
EOF

cat >> "$OUTPUT_FILE" << 'EOF'

# ==========================================
# RATE LIMITING - Production
# ==========================================
RATE_LIMIT_ENABLED=true
RATE_LIMIT_MAX=1000
RATE_LIMIT_WINDOW_MS=900000

# ==========================================
# ANALYTICS - Production
# ==========================================
NEXT_PUBLIC_GA_MEASUREMENT_ID=G-XXXXXXXXXX

# ==========================================
# FEATURE FLAGS - Production
# ==========================================
NEXT_PUBLIC_ENABLE_AI_AGENTS=true
NEXT_PUBLIC_ENABLE_WHATSAPP=true
NEXT_PUBLIC_ENABLE_PAYMENTS=true
NEXT_PUBLIC_ENABLE_OAUTH=true

# ==========================================
# COMPLIANCE - Production Settings
# ==========================================
PCI_COMPLIANCE_ENABLED=true
GDPR_COMPLIANCE_ENABLED=true
POPIA_COMPLIANCE_ENABLED=true
COMPLIANCE_MODE=enterprise

# ==========================================
# EMAIL SERVICE - Production
# ==========================================
EOF

SMTP_HOST=$(get_vault_secret "$SECRETS_PATH" "SMTP_HOST")
SMTP_USER=$(get_vault_secret "$SECRETS_PATH" "SMTP_USER")
SMTP_PASS=$(get_vault_secret "$SECRETS_PATH" "SMTP_PASS")

cat >> "$OUTPUT_FILE" << EOF
SMTP_HOST=${SMTP_HOST:-smtp.your-email-provider.com}
SMTP_PORT=587
SMTP_USER=${SMTP_USER:-your-production-email@appointmentbooking.co.za}
SMTP_PASS=${SMTP_PASS:-your-production-email-password}
EMAIL_FROM=noreply@appointmentbooking.co.za
EOF

cat >> "$OUTPUT_FILE" << 'EOF'

# ==========================================
# WEBHOOK ENDPOINTS - Production URLs
# ==========================================
CALENDAR_WEBHOOK_SECRET=your-production-calendar-webhook-secret
AISENSY_WEBHOOK_URL=https://appointmentbooking.co.za/api/webhooks/aisensy

# ==========================================
# MONITORING & ALERTING - Production
# ==========================================
EOF

HEALTH_CHECK_SECRET=$(get_vault_secret "$SECRETS_PATH" "HEALTH_CHECK_SECRET")
MONITORING_WEBHOOK_URL=$(get_vault_secret "$SECRETS_PATH" "MONITORING_WEBHOOK_URL")

cat >> "$OUTPUT_FILE" << EOF
HEALTH_CHECK_SECRET=${HEALTH_CHECK_SECRET:-your-production-health-check-secret}
MONITORING_WEBHOOK_URL=${MONITORING_WEBHOOK_URL:-https://hooks.slack.com/your-production-webhook}
ALERT_EMAIL=alerts@appointmentbooking.co.za
EOF

cat >> "$OUTPUT_FILE" << 'EOF'

# ==========================================
# SECURITY HEADERS - Production
# ==========================================
EOF

CSP_NONCE_SECRET=$(get_vault_secret "$SECRETS_PATH" "CSP_NONCE_SECRET")
SECURE_COOKIE_SECRET=$(get_vault_secret "$SECRETS_PATH" "SECURE_COOKIE_SECRET")

cat >> "$OUTPUT_FILE" << EOF
CSP_NONCE_SECRET=${CSP_NONCE_SECRET:-your-production-csp-nonce-secret}
SECURE_COOKIE_SECRET=${SECURE_COOKIE_SECRET:-your-production-secure-cookie-secret}

# ==========================================
# ENCRYPTION KEYS - From Vault
# ==========================================
ENCRYPTION_KEY=${ENCRYPTION_KEY:-your-production-encryption-key}
EOF

echo ""
echo "=========================================="
echo "Secrets Retrieval Complete"
echo "=========================================="
echo -e "${GREEN}Output file: $OUTPUT_FILE${NC}"
echo ""
echo "Next steps:"
echo "1. Review $OUTPUT_FILE for any empty values"
echo "2. Manually add any missing secrets from Vault"
echo "3. Deploy to Cloudflare Pages:"
echo "   npx wrangler pages secret bulk $OUTPUT_FILE --project-name=appointment-booking-coza"
echo ""
echo -e "${YELLOW}Warning: Delete $OUTPUT_FILE after deployment${NC}"

# Count missing secrets
MISSING_COUNT=0
while IFS= read -r line; do
    if [[ "$line" == *"=your-"* ]] || [[ "$line" == *"=your-production-"* ]] || [[ "$line" == *"=pk_live_"* ]] || [[ "$line" == *"=sk_live_"* ]]; then
        MISSING_COUNT=$((MISSING_COUNT + 1))
    fi
done < "$OUTPUT_FILE"

if [ $MISSING_COUNT -gt 0 ]; then
    echo ""
    echo -e "${YELLOW}⚠ $MISSING_COUNT secrets still need to be populated${NC}"
    echo "These values were not found in Vault and need to be added manually."
fi
